version: "2"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bundle exec puma -C config/puma.rb
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /var/tmp
      # socketファイルの共有
      - sockets:/app/tmp/sockets
    stdin_open: true
    tty: true
    depends_on:
      - db
    extends:
      file: ./docker/mysql/password.yml
      service: password

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3316:3306"
    volumes:
      - db_data:/var/lib/mysql
    extends:
      file: ./docker/mysql/password.yml
      service: password

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
      #socketファイルの共有
    volumes:
      - sockets:/app/tmp/sockets
    depends_on:
      - app

volumes:
  db_data:
  sockets:
  mysql_data: