version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.3.0
  aws-ecs: circleci/aws-ecs@7.2.0
  aws-cli: circleci/aws-cli@4.0.0

workflows:
  build_and_deploy_all:
    jobs:
      # 1. Nginxイメージのビルドとプッシュ
      - aws-ecr/build_and_push_image:
          name: build_nginx_image
          dockerfile: Dockerfile
          path: ./docker/nginx
          repo: onsen-nginx-tf
          # ▼▼▼ ここを修正 ▼▼▼
          tag: "latest,${CIRCLE_SHA1}"
          # ▲▲▲ 修正ここまで ▲▲▲
          filters:
            branches:
              only: master
          auth:
            - aws-cli/setup

      # 2. Railsイメージのビルドとプッシュ
      - aws-ecr/build_and_push_image:
          name: build_rails_image
          build-args: RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
          dockerfile: ./docker/rails/Dockerfile
          path: .
          repo: onsen-rails-tf
          # ▼▼▼ ここを修正 ▼▼▼
          tag: "latest,${CIRCLE_SHA1}"
          # ▲▲▲ 修正ここまで ▲▲▲
          filters:
            branches:
              only: master
          auth:
            - aws-cli/setup

      # 3. ECSサービスへのデプロイ
      - aws-ecs/deploy_service_update:
          requires:
            - build_nginx_image
            - build_rails_image
          family: "onsen-task-tf"
          cluster: "onsen-cluster-tf"
          service_name: "onsen-service"
          container_image_name_updates: "container=onsen-nginx-container,tag=${CIRCLE_SHA1},container=onsen-container,tag=${CIRCLE_SHA1}"
          filters:
            branches:
              only: master
          auth:
            - aws-cli/setup