version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.7.0 
  aws-ecs: circleci/aws-ecs@2.2.1
  aws-cli: circleci/aws-cli@5.4.1


jobs:
  # 問題箇所
  db_migrate:  
    docker:
      - image: cimg/aws/client:latest
        auth:
          username: ${DOCKERHUB_USER}
          password: ${DOCKERHUB_PASS}
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Run DB Migrations
          command: |
            aws ecs run-task --cluster onsen-cluster --task-definition onsen-task \
            --launch-type EC2 \
            --overrides '{"containerOverrides": [{"name": "onsen-container", "command": ["rails", "db:migrate"]}]}'

workflows:
  build_and_deploy_all:
    jobs:
      # 1. Nginxイメージのビルドとプッシュ
      - aws-ecr/build_and_push_image:
          name: build_nginx_image
          dockerfile: ./docker/nginx/Dockerfile
          repo: onsen-nginx
          tag: "${CIRCLE_SHA1}"
          filters:
            branches:
              only: master
          auth:
            - aws-cli/setup

      # 2. Railsイメージのビルドとプッシュ
      - aws-ecr/build_and_push_image:
          name: build_rails_image
          dockerfile: ./docker/rails/Dockerfile
          repo: onsen
          tag: "${CIRCLE_SHA1}"
          filters:
            branches:
              only: master
          auth:
            - aws-cli/setup
      
      # 3. データベースマイグレーションの実行
      - db_migrate:
          requires:
            - build_nginx_image
            - build_rails_image

      # 4. ECSサービスへのデプロイ
      - aws-ecs/deploy-service-update:
          requires:
            - db_migrate
          family: "onsen-task" 
          cluster-name: "onsen-cluster"
          service-name: "onsen-service"
          container-image-name-updates: |
            container=onsen-nginx-container,tag=${CIRCLE_SHA1}
            container=onsen-container,tag=${CIRCLE_SHA1}