

default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: ‘root’
  password: ‘yosshi46’
  socket: /var/run/mysqld/mysqld.sock
  host: ‘localhost’
  # 文字コードをutf8に統一
  charset: utf8mb4
development:
  <<: *default
  database: onsen_development
  username: root
  password: yosshi46
  host: localhost
  <<: *default
  database: onsen_development
  username: root
  password: yosshi46
  host: localhost
production:
  <<: *default
  database: onsen_development
  username: root
  password: yosshi46
  host: localhost
  adapter: mysql2
  encoding: utf8mb4
  socket: /var/run/mysqld/mysqld.sock
  port: 3306